name: build and test
on:
  push:
    branches:
      - feature/*
      - master
jobs:
  publish:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        id: setup_dotnet
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: | 
              6.0.x
              7.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test EpubCore
        run: dotnet test ./EpubCore.Tests/EpubCore.Tests.csproj --no-restore --verbosity normal
      - name: Test EpubCoreCli
        run: dotnet test ./EpubCore.Cli.Tests/EpubCore.Cli.Tests.csproj --no-restore --verbosity normal